/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RetentionJobDeletedRestorePoint struct for RetentionJobDeletedRestorePoint
type RetentionJobDeletedRestorePoint struct {
	Name *string `json:"name,omitempty"`
	Status *SessionItemsStatuses `json:"status,omitempty"`
	Region *string `json:"region,omitempty"`
	Embedded *RetentionJobDeletedRestorePointEmbedded `json:"_embedded,omitempty"`
}

// NewRetentionJobDeletedRestorePoint instantiates a new RetentionJobDeletedRestorePoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetentionJobDeletedRestorePoint() *RetentionJobDeletedRestorePoint {
	this := RetentionJobDeletedRestorePoint{}
	return &this
}

// NewRetentionJobDeletedRestorePointWithDefaults instantiates a new RetentionJobDeletedRestorePoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetentionJobDeletedRestorePointWithDefaults() *RetentionJobDeletedRestorePoint {
	this := RetentionJobDeletedRestorePoint{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RetentionJobDeletedRestorePoint) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionJobDeletedRestorePoint) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RetentionJobDeletedRestorePoint) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RetentionJobDeletedRestorePoint) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RetentionJobDeletedRestorePoint) GetStatus() SessionItemsStatuses {
	if o == nil || o.Status == nil {
		var ret SessionItemsStatuses
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionJobDeletedRestorePoint) GetStatusOk() (*SessionItemsStatuses, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RetentionJobDeletedRestorePoint) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SessionItemsStatuses and assigns it to the Status field.
func (o *RetentionJobDeletedRestorePoint) SetStatus(v SessionItemsStatuses) {
	o.Status = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *RetentionJobDeletedRestorePoint) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionJobDeletedRestorePoint) GetRegionOk() (*string, bool) {
	if o == nil || o.Region == nil {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *RetentionJobDeletedRestorePoint) HasRegion() bool {
	if o != nil && o.Region != nil {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *RetentionJobDeletedRestorePoint) SetRegion(v string) {
	o.Region = &v
}

// GetEmbedded returns the Embedded field value if set, zero value otherwise.
func (o *RetentionJobDeletedRestorePoint) GetEmbedded() RetentionJobDeletedRestorePointEmbedded {
	if o == nil || o.Embedded == nil {
		var ret RetentionJobDeletedRestorePointEmbedded
		return ret
	}
	return *o.Embedded
}

// GetEmbeddedOk returns a tuple with the Embedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionJobDeletedRestorePoint) GetEmbeddedOk() (*RetentionJobDeletedRestorePointEmbedded, bool) {
	if o == nil || o.Embedded == nil {
		return nil, false
	}
	return o.Embedded, true
}

// HasEmbedded returns a boolean if a field has been set.
func (o *RetentionJobDeletedRestorePoint) HasEmbedded() bool {
	if o != nil && o.Embedded != nil {
		return true
	}

	return false
}

// SetEmbedded gets a reference to the given RetentionJobDeletedRestorePointEmbedded and assigns it to the Embedded field.
func (o *RetentionJobDeletedRestorePoint) SetEmbedded(v RetentionJobDeletedRestorePointEmbedded) {
	o.Embedded = &v
}

func (o RetentionJobDeletedRestorePoint) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Region != nil {
		toSerialize["region"] = o.Region
	}
	if o.Embedded != nil {
		toSerialize["_embedded"] = o.Embedded
	}
	return json.Marshal(toSerialize)
}

type NullableRetentionJobDeletedRestorePoint struct {
	value *RetentionJobDeletedRestorePoint
	isSet bool
}

func (v NullableRetentionJobDeletedRestorePoint) Get() *RetentionJobDeletedRestorePoint {
	return v.value
}

func (v *NullableRetentionJobDeletedRestorePoint) Set(val *RetentionJobDeletedRestorePoint) {
	v.value = val
	v.isSet = true
}

func (v NullableRetentionJobDeletedRestorePoint) IsSet() bool {
	return v.isSet
}

func (v *NullableRetentionJobDeletedRestorePoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetentionJobDeletedRestorePoint(val *RetentionJobDeletedRestorePoint) *NullableRetentionJobDeletedRestorePoint {
	return &NullableRetentionJobDeletedRestorePoint{value: val, isSet: true}
}

func (v NullableRetentionJobDeletedRestorePoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetentionJobDeletedRestorePoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


