/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CloudSecurityGroup struct for CloudSecurityGroup
type CloudSecurityGroup struct {
	ResourceId string `json:"resourceId"`
	CloudNetworkResourceId string `json:"cloudNetworkResourceId"`
	Name string `json:"name"`
}

// NewCloudSecurityGroup instantiates a new CloudSecurityGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudSecurityGroup(resourceId string, cloudNetworkResourceId string, name string) *CloudSecurityGroup {
	this := CloudSecurityGroup{}
	this.ResourceId = resourceId
	this.CloudNetworkResourceId = cloudNetworkResourceId
	this.Name = name
	return &this
}

// NewCloudSecurityGroupWithDefaults instantiates a new CloudSecurityGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudSecurityGroupWithDefaults() *CloudSecurityGroup {
	this := CloudSecurityGroup{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *CloudSecurityGroup) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *CloudSecurityGroup) GetResourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *CloudSecurityGroup) SetResourceId(v string) {
	o.ResourceId = v
}

// GetCloudNetworkResourceId returns the CloudNetworkResourceId field value
func (o *CloudSecurityGroup) GetCloudNetworkResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudNetworkResourceId
}

// GetCloudNetworkResourceIdOk returns a tuple with the CloudNetworkResourceId field value
// and a boolean to check if the value has been set.
func (o *CloudSecurityGroup) GetCloudNetworkResourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CloudNetworkResourceId, true
}

// SetCloudNetworkResourceId sets field value
func (o *CloudSecurityGroup) SetCloudNetworkResourceId(v string) {
	o.CloudNetworkResourceId = v
}

// GetName returns the Name field value
func (o *CloudSecurityGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudSecurityGroup) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudSecurityGroup) SetName(v string) {
	o.Name = v
}

func (o CloudSecurityGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["resourceId"] = o.ResourceId
	}
	if true {
		toSerialize["cloudNetworkResourceId"] = o.CloudNetworkResourceId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCloudSecurityGroup struct {
	value *CloudSecurityGroup
	isSet bool
}

func (v NullableCloudSecurityGroup) Get() *CloudSecurityGroup {
	return v.value
}

func (v *NullableCloudSecurityGroup) Set(val *CloudSecurityGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudSecurityGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudSecurityGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudSecurityGroup(val *CloudSecurityGroup) *NullableCloudSecurityGroup {
	return &NullableCloudSecurityGroup{value: val, isSet: true}
}

func (v NullableCloudSecurityGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudSecurityGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


