/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// DailyScheduleKinds the model 'DailyScheduleKinds'
type DailyScheduleKinds string

// List of DailyScheduleKinds
const (
	DAILYSCHEDULEKINDS_EVERYDAY DailyScheduleKinds = "Everyday"
	DAILYSCHEDULEKINDS_WEEK_DAYS DailyScheduleKinds = "WeekDays"
	DAILYSCHEDULEKINDS_SELECTED_DAYS DailyScheduleKinds = "SelectedDays"
)

func (v *DailyScheduleKinds) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DailyScheduleKinds(value)
	for _, existing := range []DailyScheduleKinds{ "Everyday", "WeekDays", "SelectedDays",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DailyScheduleKinds", value)
}

// Ptr returns reference to DailyScheduleKinds value
func (v DailyScheduleKinds) Ptr() *DailyScheduleKinds {
	return &v
}

type NullableDailyScheduleKinds struct {
	value *DailyScheduleKinds
	isSet bool
}

func (v NullableDailyScheduleKinds) Get() *DailyScheduleKinds {
	return v.value
}

func (v *NullableDailyScheduleKinds) Set(val *DailyScheduleKinds) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyScheduleKinds) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyScheduleKinds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyScheduleKinds(val *DailyScheduleKinds) *NullableDailyScheduleKinds {
	return &NullableDailyScheduleKinds{value: val, isSet: true}
}

func (v NullableDailyScheduleKinds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyScheduleKinds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

