/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// JobTypes the model 'JobTypes'
type JobTypes string

// List of JobTypes
const (
	JOBTYPES_BACKUP JobTypes = "Backup"
	JOBTYPES_SNAPSHOT JobTypes = "Snapshot"
	JOBTYPES_MANUAL_SNAPSHOT JobTypes = "ManualSnapshot"
	JOBTYPES_REPLICA JobTypes = "Replica"
)

func (v *JobTypes) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JobTypes(value)
	for _, existing := range []JobTypes{ "Backup", "Snapshot", "ManualSnapshot", "Replica",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid JobTypes", value)
}

// Ptr returns reference to JobTypes value
func (v JobTypes) Ptr() *JobTypes {
	return &v
}

type NullableJobTypes struct {
	value *JobTypes
	isSet bool
}

func (v NullableJobTypes) Get() *JobTypes {
	return v.value
}

func (v *NullableJobTypes) Set(val *JobTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableJobTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableJobTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobTypes(val *JobTypes) *NullableJobTypes {
	return &NullableJobTypes{value: val, isSet: true}
}

func (v NullableJobTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

