/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SessionEmbeddedResources struct for SessionEmbeddedResources
type SessionEmbeddedResources struct {
	BackupJobInfo *Link `json:"backupJobInfo,omitempty"`
	RestoreJobInfo *Link `json:"restoreJobInfo,omitempty"`
	RetentionJobDeletedRestorePoints *Link `json:"retentionJobDeletedRestorePoints,omitempty"`
}

// NewSessionEmbeddedResources instantiates a new SessionEmbeddedResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionEmbeddedResources() *SessionEmbeddedResources {
	this := SessionEmbeddedResources{}
	return &this
}

// NewSessionEmbeddedResourcesWithDefaults instantiates a new SessionEmbeddedResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionEmbeddedResourcesWithDefaults() *SessionEmbeddedResources {
	this := SessionEmbeddedResources{}
	return &this
}

// GetBackupJobInfo returns the BackupJobInfo field value if set, zero value otherwise.
func (o *SessionEmbeddedResources) GetBackupJobInfo() Link {
	if o == nil || o.BackupJobInfo == nil {
		var ret Link
		return ret
	}
	return *o.BackupJobInfo
}

// GetBackupJobInfoOk returns a tuple with the BackupJobInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionEmbeddedResources) GetBackupJobInfoOk() (*Link, bool) {
	if o == nil || o.BackupJobInfo == nil {
		return nil, false
	}
	return o.BackupJobInfo, true
}

// HasBackupJobInfo returns a boolean if a field has been set.
func (o *SessionEmbeddedResources) HasBackupJobInfo() bool {
	if o != nil && o.BackupJobInfo != nil {
		return true
	}

	return false
}

// SetBackupJobInfo gets a reference to the given Link and assigns it to the BackupJobInfo field.
func (o *SessionEmbeddedResources) SetBackupJobInfo(v Link) {
	o.BackupJobInfo = &v
}

// GetRestoreJobInfo returns the RestoreJobInfo field value if set, zero value otherwise.
func (o *SessionEmbeddedResources) GetRestoreJobInfo() Link {
	if o == nil || o.RestoreJobInfo == nil {
		var ret Link
		return ret
	}
	return *o.RestoreJobInfo
}

// GetRestoreJobInfoOk returns a tuple with the RestoreJobInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionEmbeddedResources) GetRestoreJobInfoOk() (*Link, bool) {
	if o == nil || o.RestoreJobInfo == nil {
		return nil, false
	}
	return o.RestoreJobInfo, true
}

// HasRestoreJobInfo returns a boolean if a field has been set.
func (o *SessionEmbeddedResources) HasRestoreJobInfo() bool {
	if o != nil && o.RestoreJobInfo != nil {
		return true
	}

	return false
}

// SetRestoreJobInfo gets a reference to the given Link and assigns it to the RestoreJobInfo field.
func (o *SessionEmbeddedResources) SetRestoreJobInfo(v Link) {
	o.RestoreJobInfo = &v
}

// GetRetentionJobDeletedRestorePoints returns the RetentionJobDeletedRestorePoints field value if set, zero value otherwise.
func (o *SessionEmbeddedResources) GetRetentionJobDeletedRestorePoints() Link {
	if o == nil || o.RetentionJobDeletedRestorePoints == nil {
		var ret Link
		return ret
	}
	return *o.RetentionJobDeletedRestorePoints
}

// GetRetentionJobDeletedRestorePointsOk returns a tuple with the RetentionJobDeletedRestorePoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionEmbeddedResources) GetRetentionJobDeletedRestorePointsOk() (*Link, bool) {
	if o == nil || o.RetentionJobDeletedRestorePoints == nil {
		return nil, false
	}
	return o.RetentionJobDeletedRestorePoints, true
}

// HasRetentionJobDeletedRestorePoints returns a boolean if a field has been set.
func (o *SessionEmbeddedResources) HasRetentionJobDeletedRestorePoints() bool {
	if o != nil && o.RetentionJobDeletedRestorePoints != nil {
		return true
	}

	return false
}

// SetRetentionJobDeletedRestorePoints gets a reference to the given Link and assigns it to the RetentionJobDeletedRestorePoints field.
func (o *SessionEmbeddedResources) SetRetentionJobDeletedRestorePoints(v Link) {
	o.RetentionJobDeletedRestorePoints = &v
}

func (o SessionEmbeddedResources) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BackupJobInfo != nil {
		toSerialize["backupJobInfo"] = o.BackupJobInfo
	}
	if o.RestoreJobInfo != nil {
		toSerialize["restoreJobInfo"] = o.RestoreJobInfo
	}
	if o.RetentionJobDeletedRestorePoints != nil {
		toSerialize["retentionJobDeletedRestorePoints"] = o.RetentionJobDeletedRestorePoints
	}
	return json.Marshal(toSerialize)
}

type NullableSessionEmbeddedResources struct {
	value *SessionEmbeddedResources
	isSet bool
}

func (v NullableSessionEmbeddedResources) Get() *SessionEmbeddedResources {
	return v.value
}

func (v *NullableSessionEmbeddedResources) Set(val *SessionEmbeddedResources) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionEmbeddedResources) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionEmbeddedResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionEmbeddedResources(val *SessionEmbeddedResources) *NullableSessionEmbeddedResources {
	return &NullableSessionEmbeddedResources{value: val, isSet: true}
}

func (v NullableSessionEmbeddedResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionEmbeddedResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


