/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CloudNetworksPage struct for CloudNetworksPage
type CloudNetworksPage struct {
	TotalCount int32 `json:"totalCount"`
	Results []CloudNetwork `json:"results"`
	Links *[]Link `json:"_links,omitempty"`
}

// NewCloudNetworksPage instantiates a new CloudNetworksPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudNetworksPage(totalCount int32, results []CloudNetwork) *CloudNetworksPage {
	this := CloudNetworksPage{}
	this.TotalCount = totalCount
	this.Results = results
	return &this
}

// NewCloudNetworksPageWithDefaults instantiates a new CloudNetworksPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudNetworksPageWithDefaults() *CloudNetworksPage {
	this := CloudNetworksPage{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *CloudNetworksPage) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *CloudNetworksPage) GetTotalCountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *CloudNetworksPage) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetResults returns the Results field value
func (o *CloudNetworksPage) GetResults() []CloudNetwork {
	if o == nil {
		var ret []CloudNetwork
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *CloudNetworksPage) GetResultsOk() (*[]CloudNetwork, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Results, true
}

// SetResults sets field value
func (o *CloudNetworksPage) SetResults(v []CloudNetwork) {
	o.Results = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CloudNetworksPage) GetLinks() []Link {
	if o == nil || o.Links == nil {
		var ret []Link
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudNetworksPage) GetLinksOk() (*[]Link, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CloudNetworksPage) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Link and assigns it to the Links field.
func (o *CloudNetworksPage) SetLinks(v []Link) {
	o.Links = &v
}

func (o CloudNetworksPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalCount"] = o.TotalCount
	}
	if true {
		toSerialize["results"] = o.Results
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableCloudNetworksPage struct {
	value *CloudNetworksPage
	isSet bool
}

func (v NullableCloudNetworksPage) Get() *CloudNetworksPage {
	return v.value
}

func (v *NullableCloudNetworksPage) Set(val *CloudNetworksPage) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudNetworksPage) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudNetworksPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudNetworksPage(val *CloudNetworksPage) *NullableCloudNetworksPage {
	return &NullableCloudNetworksPage{value: val, isSet: true}
}

func (v NullableCloudNetworksPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudNetworksPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


