/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AmazonAccountAccessKeysUpdateSpec struct for AmazonAccountAccessKeysUpdateSpec
type AmazonAccountAccessKeysUpdateSpec struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
	DefaultRegionType RegionTypes `json:"defaultRegionType"`
}

// NewAmazonAccountAccessKeysUpdateSpec instantiates a new AmazonAccountAccessKeysUpdateSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonAccountAccessKeysUpdateSpec(accessKey string, secretKey string, defaultRegionType RegionTypes) *AmazonAccountAccessKeysUpdateSpec {
	this := AmazonAccountAccessKeysUpdateSpec{}
	this.AccessKey = accessKey
	this.SecretKey = secretKey
	this.DefaultRegionType = defaultRegionType
	return &this
}

// NewAmazonAccountAccessKeysUpdateSpecWithDefaults instantiates a new AmazonAccountAccessKeysUpdateSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonAccountAccessKeysUpdateSpecWithDefaults() *AmazonAccountAccessKeysUpdateSpec {
	this := AmazonAccountAccessKeysUpdateSpec{}
	return &this
}

// GetAccessKey returns the AccessKey field value
func (o *AmazonAccountAccessKeysUpdateSpec) GetAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value
// and a boolean to check if the value has been set.
func (o *AmazonAccountAccessKeysUpdateSpec) GetAccessKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccessKey, true
}

// SetAccessKey sets field value
func (o *AmazonAccountAccessKeysUpdateSpec) SetAccessKey(v string) {
	o.AccessKey = v
}

// GetSecretKey returns the SecretKey field value
func (o *AmazonAccountAccessKeysUpdateSpec) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *AmazonAccountAccessKeysUpdateSpec) GetSecretKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *AmazonAccountAccessKeysUpdateSpec) SetSecretKey(v string) {
	o.SecretKey = v
}

// GetDefaultRegionType returns the DefaultRegionType field value
func (o *AmazonAccountAccessKeysUpdateSpec) GetDefaultRegionType() RegionTypes {
	if o == nil {
		var ret RegionTypes
		return ret
	}

	return o.DefaultRegionType
}

// GetDefaultRegionTypeOk returns a tuple with the DefaultRegionType field value
// and a boolean to check if the value has been set.
func (o *AmazonAccountAccessKeysUpdateSpec) GetDefaultRegionTypeOk() (*RegionTypes, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DefaultRegionType, true
}

// SetDefaultRegionType sets field value
func (o *AmazonAccountAccessKeysUpdateSpec) SetDefaultRegionType(v RegionTypes) {
	o.DefaultRegionType = v
}

func (o AmazonAccountAccessKeysUpdateSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accessKey"] = o.AccessKey
	}
	if true {
		toSerialize["secretKey"] = o.SecretKey
	}
	if true {
		toSerialize["defaultRegionType"] = o.DefaultRegionType
	}
	return json.Marshal(toSerialize)
}

type NullableAmazonAccountAccessKeysUpdateSpec struct {
	value *AmazonAccountAccessKeysUpdateSpec
	isSet bool
}

func (v NullableAmazonAccountAccessKeysUpdateSpec) Get() *AmazonAccountAccessKeysUpdateSpec {
	return v.value
}

func (v *NullableAmazonAccountAccessKeysUpdateSpec) Set(val *AmazonAccountAccessKeysUpdateSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonAccountAccessKeysUpdateSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonAccountAccessKeysUpdateSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonAccountAccessKeysUpdateSpec(val *AmazonAccountAccessKeysUpdateSpec) *NullableAmazonAccountAccessKeysUpdateSpec {
	return &NullableAmazonAccountAccessKeysUpdateSpec{value: val, isSet: true}
}

func (v NullableAmazonAccountAccessKeysUpdateSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonAccountAccessKeysUpdateSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


