/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// VirtualMachinesFilters struct for VirtualMachinesFilters
type VirtualMachinesFilters struct {
	SearchPattern *string `json:"SearchPattern,omitempty"`
	ProtectionStatus *[]VirtualMachineProtectionStatuses `json:"ProtectionStatus,omitempty"`
	BackupDestination *[]BackupDestinations `json:"BackupDestination,omitempty"`
	BackupState *string `json:"BackupState,omitempty"`
	Offset *int32 `json:"Offset,omitempty"`
	Limit *int32 `json:"Limit,omitempty"`
	Sort *[]VirtualMachinesSortColumns `json:"Sort,omitempty"`
}

// NewVirtualMachinesFilters instantiates a new VirtualMachinesFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualMachinesFilters() *VirtualMachinesFilters {
	this := VirtualMachinesFilters{}
	return &this
}

// NewVirtualMachinesFiltersWithDefaults instantiates a new VirtualMachinesFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualMachinesFiltersWithDefaults() *VirtualMachinesFilters {
	this := VirtualMachinesFilters{}
	return &this
}

// GetSearchPattern returns the SearchPattern field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetSearchPattern() string {
	if o == nil || o.SearchPattern == nil {
		var ret string
		return ret
	}
	return *o.SearchPattern
}

// GetSearchPatternOk returns a tuple with the SearchPattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetSearchPatternOk() (*string, bool) {
	if o == nil || o.SearchPattern == nil {
		return nil, false
	}
	return o.SearchPattern, true
}

// HasSearchPattern returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasSearchPattern() bool {
	if o != nil && o.SearchPattern != nil {
		return true
	}

	return false
}

// SetSearchPattern gets a reference to the given string and assigns it to the SearchPattern field.
func (o *VirtualMachinesFilters) SetSearchPattern(v string) {
	o.SearchPattern = &v
}

// GetProtectionStatus returns the ProtectionStatus field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetProtectionStatus() []VirtualMachineProtectionStatuses {
	if o == nil || o.ProtectionStatus == nil {
		var ret []VirtualMachineProtectionStatuses
		return ret
	}
	return *o.ProtectionStatus
}

// GetProtectionStatusOk returns a tuple with the ProtectionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetProtectionStatusOk() (*[]VirtualMachineProtectionStatuses, bool) {
	if o == nil || o.ProtectionStatus == nil {
		return nil, false
	}
	return o.ProtectionStatus, true
}

// HasProtectionStatus returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasProtectionStatus() bool {
	if o != nil && o.ProtectionStatus != nil {
		return true
	}

	return false
}

// SetProtectionStatus gets a reference to the given []VirtualMachineProtectionStatuses and assigns it to the ProtectionStatus field.
func (o *VirtualMachinesFilters) SetProtectionStatus(v []VirtualMachineProtectionStatuses) {
	o.ProtectionStatus = &v
}

// GetBackupDestination returns the BackupDestination field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetBackupDestination() []BackupDestinations {
	if o == nil || o.BackupDestination == nil {
		var ret []BackupDestinations
		return ret
	}
	return *o.BackupDestination
}

// GetBackupDestinationOk returns a tuple with the BackupDestination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetBackupDestinationOk() (*[]BackupDestinations, bool) {
	if o == nil || o.BackupDestination == nil {
		return nil, false
	}
	return o.BackupDestination, true
}

// HasBackupDestination returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasBackupDestination() bool {
	if o != nil && o.BackupDestination != nil {
		return true
	}

	return false
}

// SetBackupDestination gets a reference to the given []BackupDestinations and assigns it to the BackupDestination field.
func (o *VirtualMachinesFilters) SetBackupDestination(v []BackupDestinations) {
	o.BackupDestination = &v
}

// GetBackupState returns the BackupState field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetBackupState() string {
	if o == nil || o.BackupState == nil {
		var ret string
		return ret
	}
	return *o.BackupState
}

// GetBackupStateOk returns a tuple with the BackupState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetBackupStateOk() (*string, bool) {
	if o == nil || o.BackupState == nil {
		return nil, false
	}
	return o.BackupState, true
}

// HasBackupState returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasBackupState() bool {
	if o != nil && o.BackupState != nil {
		return true
	}

	return false
}

// SetBackupState gets a reference to the given string and assigns it to the BackupState field.
func (o *VirtualMachinesFilters) SetBackupState(v string) {
	o.BackupState = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *VirtualMachinesFilters) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *VirtualMachinesFilters) SetLimit(v int32) {
	o.Limit = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *VirtualMachinesFilters) GetSort() []VirtualMachinesSortColumns {
	if o == nil || o.Sort == nil {
		var ret []VirtualMachinesSortColumns
		return ret
	}
	return *o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualMachinesFilters) GetSortOk() (*[]VirtualMachinesSortColumns, bool) {
	if o == nil || o.Sort == nil {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *VirtualMachinesFilters) HasSort() bool {
	if o != nil && o.Sort != nil {
		return true
	}

	return false
}

// SetSort gets a reference to the given []VirtualMachinesSortColumns and assigns it to the Sort field.
func (o *VirtualMachinesFilters) SetSort(v []VirtualMachinesSortColumns) {
	o.Sort = &v
}

func (o VirtualMachinesFilters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SearchPattern != nil {
		toSerialize["SearchPattern"] = o.SearchPattern
	}
	if o.ProtectionStatus != nil {
		toSerialize["ProtectionStatus"] = o.ProtectionStatus
	}
	if o.BackupDestination != nil {
		toSerialize["BackupDestination"] = o.BackupDestination
	}
	if o.BackupState != nil {
		toSerialize["BackupState"] = o.BackupState
	}
	if o.Offset != nil {
		toSerialize["Offset"] = o.Offset
	}
	if o.Limit != nil {
		toSerialize["Limit"] = o.Limit
	}
	if o.Sort != nil {
		toSerialize["Sort"] = o.Sort
	}
	return json.Marshal(toSerialize)
}

type NullableVirtualMachinesFilters struct {
	value *VirtualMachinesFilters
	isSet bool
}

func (v NullableVirtualMachinesFilters) Get() *VirtualMachinesFilters {
	return v.value
}

func (v *NullableVirtualMachinesFilters) Set(val *VirtualMachinesFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualMachinesFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualMachinesFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualMachinesFilters(val *VirtualMachinesFilters) *NullableVirtualMachinesFilters {
	return &NullableVirtualMachinesFilters{value: val, isSet: true}
}

func (v NullableVirtualMachinesFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualMachinesFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


