/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// DailyReplicaScheduleSettings struct for DailyReplicaScheduleSettings
type DailyReplicaScheduleSettings struct {
	Retention PointsRetentionOptions `json:"retention"`
	Schedule DailySchedule `json:"schedule"`
}

// NewDailyReplicaScheduleSettings instantiates a new DailyReplicaScheduleSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyReplicaScheduleSettings(retention PointsRetentionOptions, schedule DailySchedule) *DailyReplicaScheduleSettings {
	this := DailyReplicaScheduleSettings{}
	this.Retention = retention
	this.Schedule = schedule
	return &this
}

// NewDailyReplicaScheduleSettingsWithDefaults instantiates a new DailyReplicaScheduleSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyReplicaScheduleSettingsWithDefaults() *DailyReplicaScheduleSettings {
	this := DailyReplicaScheduleSettings{}
	return &this
}

// GetRetention returns the Retention field value
func (o *DailyReplicaScheduleSettings) GetRetention() PointsRetentionOptions {
	if o == nil {
		var ret PointsRetentionOptions
		return ret
	}

	return o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value
// and a boolean to check if the value has been set.
func (o *DailyReplicaScheduleSettings) GetRetentionOk() (*PointsRetentionOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Retention, true
}

// SetRetention sets field value
func (o *DailyReplicaScheduleSettings) SetRetention(v PointsRetentionOptions) {
	o.Retention = v
}

// GetSchedule returns the Schedule field value
func (o *DailyReplicaScheduleSettings) GetSchedule() DailySchedule {
	if o == nil {
		var ret DailySchedule
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *DailyReplicaScheduleSettings) GetScheduleOk() (*DailySchedule, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *DailyReplicaScheduleSettings) SetSchedule(v DailySchedule) {
	o.Schedule = v
}

func (o DailyReplicaScheduleSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["retention"] = o.Retention
	}
	if true {
		toSerialize["schedule"] = o.Schedule
	}
	return json.Marshal(toSerialize)
}

type NullableDailyReplicaScheduleSettings struct {
	value *DailyReplicaScheduleSettings
	isSet bool
}

func (v NullableDailyReplicaScheduleSettings) Get() *DailyReplicaScheduleSettings {
	return v.value
}

func (v *NullableDailyReplicaScheduleSettings) Set(val *DailyReplicaScheduleSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyReplicaScheduleSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyReplicaScheduleSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyReplicaScheduleSettings(val *DailyReplicaScheduleSettings) *NullableDailyReplicaScheduleSettings {
	return &NullableDailyReplicaScheduleSettings{value: val, isSet: true}
}

func (v NullableDailyReplicaScheduleSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyReplicaScheduleSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


