/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ProtectedItemsSortColumns the model 'ProtectedItemsSortColumns'
type ProtectedItemsSortColumns string

// List of ProtectedItemsSortColumns
const (
	PROTECTEDITEMSSORTCOLUMNS_VIRTUAL_MACHINE_NAME_ASC ProtectedItemsSortColumns = "virtualMachineNameAsc"
	PROTECTEDITEMSSORTCOLUMNS_VIRTUAL_MACHINE_NAME_DESC ProtectedItemsSortColumns = "virtualMachineNameDesc"
	PROTECTEDITEMSSORTCOLUMNS_REGION_ASC ProtectedItemsSortColumns = "regionAsc"
	PROTECTEDITEMSSORTCOLUMNS_REGION_DESC ProtectedItemsSortColumns = "regionDesc"
)

func (v *ProtectedItemsSortColumns) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProtectedItemsSortColumns(value)
	for _, existing := range []ProtectedItemsSortColumns{ "virtualMachineNameAsc", "virtualMachineNameDesc", "regionAsc", "regionDesc",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProtectedItemsSortColumns", value)
}

// Ptr returns reference to ProtectedItemsSortColumns value
func (v ProtectedItemsSortColumns) Ptr() *ProtectedItemsSortColumns {
	return &v
}

type NullableProtectedItemsSortColumns struct {
	value *ProtectedItemsSortColumns
	isSet bool
}

func (v NullableProtectedItemsSortColumns) Get() *ProtectedItemsSortColumns {
	return v.value
}

func (v *NullableProtectedItemsSortColumns) Set(val *ProtectedItemsSortColumns) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectedItemsSortColumns) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectedItemsSortColumns) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectedItemsSortColumns(val *ProtectedItemsSortColumns) *NullableProtectedItemsSortColumns {
	return &NullableProtectedItemsSortColumns{value: val, isSet: true}
}

func (v NullableProtectedItemsSortColumns) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectedItemsSortColumns) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

