/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// LicenseAgreements struct for LicenseAgreements
type LicenseAgreements struct {
	Items *[]LicenseAgreement `json:"items,omitempty"`
}

// NewLicenseAgreements instantiates a new LicenseAgreements object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicenseAgreements() *LicenseAgreements {
	this := LicenseAgreements{}
	return &this
}

// NewLicenseAgreementsWithDefaults instantiates a new LicenseAgreements object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseAgreementsWithDefaults() *LicenseAgreements {
	this := LicenseAgreements{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *LicenseAgreements) GetItems() []LicenseAgreement {
	if o == nil || o.Items == nil {
		var ret []LicenseAgreement
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseAgreements) GetItemsOk() (*[]LicenseAgreement, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *LicenseAgreements) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []LicenseAgreement and assigns it to the Items field.
func (o *LicenseAgreements) SetItems(v []LicenseAgreement) {
	o.Items = &v
}

func (o LicenseAgreements) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableLicenseAgreements struct {
	value *LicenseAgreements
	isSet bool
}

func (v NullableLicenseAgreements) Get() *LicenseAgreements {
	return v.value
}

func (v *NullableLicenseAgreements) Set(val *LicenseAgreements) {
	v.value = val
	v.isSet = true
}

func (v NullableLicenseAgreements) IsSet() bool {
	return v.isSet
}

func (v *NullableLicenseAgreements) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicenseAgreements(val *LicenseAgreements) *NullableLicenseAgreements {
	return &NullableLicenseAgreements{value: val, isSet: true}
}

func (v NullableLicenseAgreements) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicenseAgreements) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


