/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UserDescriptionValidationSpec struct for UserDescriptionValidationSpec
type UserDescriptionValidationSpec struct {
	Description string `json:"description"`
}

// NewUserDescriptionValidationSpec instantiates a new UserDescriptionValidationSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDescriptionValidationSpec(description string) *UserDescriptionValidationSpec {
	this := UserDescriptionValidationSpec{}
	this.Description = description
	return &this
}

// NewUserDescriptionValidationSpecWithDefaults instantiates a new UserDescriptionValidationSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDescriptionValidationSpecWithDefaults() *UserDescriptionValidationSpec {
	this := UserDescriptionValidationSpec{}
	return &this
}

// GetDescription returns the Description field value
func (o *UserDescriptionValidationSpec) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *UserDescriptionValidationSpec) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *UserDescriptionValidationSpec) SetDescription(v string) {
	o.Description = v
}

func (o UserDescriptionValidationSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableUserDescriptionValidationSpec struct {
	value *UserDescriptionValidationSpec
	isSet bool
}

func (v NullableUserDescriptionValidationSpec) Get() *UserDescriptionValidationSpec {
	return v.value
}

func (v *NullableUserDescriptionValidationSpec) Set(val *UserDescriptionValidationSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDescriptionValidationSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDescriptionValidationSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDescriptionValidationSpec(val *UserDescriptionValidationSpec) *NullableUserDescriptionValidationSpec {
	return &NullableUserDescriptionValidationSpec{value: val, isSet: true}
}

func (v NullableUserDescriptionValidationSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDescriptionValidationSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


