/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// BucketsSortColumns the model 'BucketsSortColumns'
type BucketsSortColumns string

// List of BucketsSortColumns
const (
	BUCKETSSORTCOLUMNS_NAME_ASC BucketsSortColumns = "nameAsc"
	BUCKETSSORTCOLUMNS_NAME_DESC BucketsSortColumns = "nameDesc"
)

func (v *BucketsSortColumns) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BucketsSortColumns(value)
	for _, existing := range []BucketsSortColumns{ "nameAsc", "nameDesc",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BucketsSortColumns", value)
}

// Ptr returns reference to BucketsSortColumns value
func (v BucketsSortColumns) Ptr() *BucketsSortColumns {
	return &v
}

type NullableBucketsSortColumns struct {
	value *BucketsSortColumns
	isSet bool
}

func (v NullableBucketsSortColumns) Get() *BucketsSortColumns {
	return v.value
}

func (v *NullableBucketsSortColumns) Set(val *BucketsSortColumns) {
	v.value = val
	v.isSet = true
}

func (v NullableBucketsSortColumns) IsSet() bool {
	return v.isSet
}

func (v *NullableBucketsSortColumns) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBucketsSortColumns(val *BucketsSortColumns) *NullableBucketsSortColumns {
	return &NullableBucketsSortColumns{value: val, isSet: true}
}

func (v NullableBucketsSortColumns) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBucketsSortColumns) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

