/*
 * Veeam Backup for AWS public API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0-rev0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// StandardAccountsSortColumns the model 'StandardAccountsSortColumns'
type StandardAccountsSortColumns string

// List of StandardAccountsSortColumns
const (
	STANDARDACCOUNTSSORTCOLUMNS_NAME_ASC StandardAccountsSortColumns = "nameAsc"
	STANDARDACCOUNTSSORTCOLUMNS_NAME_DESC StandardAccountsSortColumns = "nameDesc"
)

func (v *StandardAccountsSortColumns) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StandardAccountsSortColumns(value)
	for _, existing := range []StandardAccountsSortColumns{ "nameAsc", "nameDesc",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StandardAccountsSortColumns", value)
}

// Ptr returns reference to StandardAccountsSortColumns value
func (v StandardAccountsSortColumns) Ptr() *StandardAccountsSortColumns {
	return &v
}

type NullableStandardAccountsSortColumns struct {
	value *StandardAccountsSortColumns
	isSet bool
}

func (v NullableStandardAccountsSortColumns) Get() *StandardAccountsSortColumns {
	return v.value
}

func (v *NullableStandardAccountsSortColumns) Set(val *StandardAccountsSortColumns) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardAccountsSortColumns) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardAccountsSortColumns) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardAccountsSortColumns(val *StandardAccountsSortColumns) *NullableStandardAccountsSortColumns {
	return &NullableStandardAccountsSortColumns{value: val, isSet: true}
}

func (v NullableStandardAccountsSortColumns) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardAccountsSortColumns) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

